spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mok?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    username: root
env: order-dev1
girl:
  name: lily
  age: 1771
